name: vynemit_flutter
description: A powerful, lightweight Flutter client for the Vynemit notification system.
version: 0.1.0
repository: https://github.com/IsaiahTek/vynemit
homepage: https://github.com/IsaiahTek/vynemit

topics:
  - notifications
  - realtime
  - websocket
  - flutter-sdk
  - messaging

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  socket_io_client: ^3.1.4
  intl: ^0.18.1
  provider: ^6.1.1 # For ChangeNotifier integration

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
